/*
 * Public surface of the Profile module. Callers import from here, never from repository or schema.
 */
export {
  achievementInput,
  createAchievementInput,
  createProfileInput,
  educationInput,
  educationStatuses,
  employmentInput,
  fieldErrorsFromZod,
  projectInput,
  skillInput,
  updateProfileInput,
  workArrangements,
  type AchievementInput,
  type CreateAchievementInput,
  type CreateProfileInput,
  type EducationInput,
  type EducationStatus,
  type EmploymentInput,
  type FieldErrors,
  type ProfileError,
  type ProjectInput,
  type Result,
  type SkillInput,
  type UpdateProfileInput,
} from "./contracts";
export {
  createAchievement,
  createProfile,
  deleteAchievement,
  deleteEducation,
  deleteEmployment,
  deleteProject,
  deleteSkill,
  getAchievement,
  getCurrentProfile,
  getEducation,
  getEmployment,
  getProject,
  getSkill,
  listAchievements,
  listEducation,
  listEmployment,
  listProjects,
  listSkills,
  saveEducation,
  saveEmployment,
  saveProject,
  saveSkill,
  updateAchievement,
  updateProfile,
  type AchievementWithSkills,
  type ProfileDeps,
} from "./service";
export type {
  AchievementRecord,
  EducationRecord,
  EmploymentRecord,
  ProfileRecord,
  ProjectRecord,
  SkillRecord,
} from "./repository";
export type { ProfilePreferences } from "./schema";
