import { sql } from "drizzle-orm";
import {
  boolean,
  check,
  foreignKey,
  index,
  integer,
  jsonb,
  pgTable,
  primaryKey,
  text,
  timestamp,
  unique,
  uuid,
} from "drizzle-orm/pg-core";

/*
 * Phase 0 tables (docs/04). Rules the database backs up:
 * - Every owned record carries profile_id. Child links use owner-aware composite foreign keys
 *   (profile_id, linked_id) -> parent (profile_id, id), so a link cannot cross profiles.
 * - An achievement has at most one context: employment or project, never both.
 * - Skill names are unique per profile after normalization.
 * - Dates are month precision: year and month are paired (both null or both set), month 1-12.
 * - Deleting employment or a project with dependent facts is restricted; deleting an achievement
 *   or a skill removes only its join rows. Deleting a profile removes everything it owns.
 * UUIDs are generated by the application; no database extension is needed.
 */

const timestamps = {
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
};

const monthDates = {
  startYear: integer("start_year"),
  startMonth: integer("start_month"),
  endYear: integer("end_year"),
  endMonth: integer("end_month"),
};

/** Check constraints for a pair of month-only start/end dates. */
function monthDateChecks(table: string) {
  return [
    check(`${table}_start_month_pair`, sql`(start_year IS NULL) = (start_month IS NULL)`),
    check(`${table}_end_month_pair`, sql`(end_year IS NULL) = (end_month IS NULL)`),
    check(
      `${table}_start_month_range`,
      sql`start_month IS NULL OR (start_month BETWEEN 1 AND 12 AND start_year BETWEEN 1900 AND 2100)`,
    ),
    check(
      `${table}_end_month_range`,
      sql`end_month IS NULL OR (end_month BETWEEN 1 AND 12 AND end_year BETWEEN 1900 AND 2100)`,
    ),
    check(
      `${table}_end_not_before_start`,
      sql`start_year IS NULL OR end_year IS NULL OR (end_year * 12 + end_month) >= (start_year * 12 + start_month)`,
    ),
  ];
}

const notBlank = (table: string, column: string) =>
  check(`${table}_${column}_not_blank`, sql.raw(`btrim(${column}) <> ''`));

export interface ProfilePreferences {
  desiredRoles?: string[];
  locations?: string[];
  workArrangement?: ("remote" | "hybrid" | "onsite")[];
  constraints?: string;
}

export const profiles = pgTable(
  "profiles",
  {
    id: uuid("id").primaryKey(),
    displayName: text("display_name").notNull(),
    headline: text("headline"),
    summary: text("summary"),
    email: text("email"),
    phone: text("phone"),
    location: text("location"),
    preferences: jsonb("preferences").$type<ProfilePreferences>().notNull().default({}),
    ...timestamps,
  },
  (t) => [notBlank("profiles", t.displayName.name)],
);

export const employment = pgTable(
  "employment",
  {
    id: uuid("id").primaryKey(),
    profileId: uuid("profile_id")
      .notNull()
      .references(() => profiles.id, { onDelete: "cascade" }),
    employerName: text("employer_name").notNull(),
    role: text("role").notNull(),
    ...monthDates,
    isCurrent: boolean("is_current").notNull().default(false),
    description: text("description"),
    ...timestamps,
  },
  (t) => [
    unique("employment_profile_id_id_unique").on(t.profileId, t.id),
    notBlank("employment", t.employerName.name),
    notBlank("employment", t.role.name),
    ...monthDateChecks("employment"),
  ],
);

export const educationStatuses = ["in_progress", "completed", "incomplete"] as const;
export type EducationStatus = (typeof educationStatuses)[number];

export const education = pgTable(
  "education",
  {
    id: uuid("id").primaryKey(),
    profileId: uuid("profile_id")
      .notNull()
      .references(() => profiles.id, { onDelete: "cascade" }),
    institution: text("institution").notNull(),
    qualification: text("qualification"),
    subject: text("subject"),
    ...monthDates,
    status: text("status", { enum: educationStatuses }).notNull().default("completed"),
    description: text("description"),
    ...timestamps,
  },
  (t) => [
    index("education_profile_id_idx").on(t.profileId),
    notBlank("education", t.institution.name),
    check("education_status_valid", sql`status IN ('in_progress', 'completed', 'incomplete')`),
    ...monthDateChecks("education"),
  ],
);

export const projects = pgTable(
  "projects",
  {
    id: uuid("id").primaryKey(),
    profileId: uuid("profile_id")
      .notNull()
      .references(() => profiles.id, { onDelete: "cascade" }),
    employmentId: uuid("employment_id"),
    name: text("name").notNull(),
    description: text("description"),
    url: text("url"),
    ...monthDates,
    ...timestamps,
  },
  (t) => [
    unique("projects_profile_id_id_unique").on(t.profileId, t.id),
    foreignKey({
      name: "projects_employment_fk",
      columns: [t.profileId, t.employmentId],
      foreignColumns: [employment.profileId, employment.id],
    }).onDelete("restrict"),
    index("projects_profile_id_employment_id_idx").on(t.profileId, t.employmentId),
    notBlank("projects", t.name.name),
    ...monthDateChecks("projects"),
  ],
);

export const achievements = pgTable(
  "achievements",
  {
    id: uuid("id").primaryKey(),
    profileId: uuid("profile_id")
      .notNull()
      .references(() => profiles.id, { onDelete: "cascade" }),
    employmentId: uuid("employment_id"),
    projectId: uuid("project_id"),
    statement: text("statement").notNull(),
    problem: text("problem"),
    action: text("action"),
    result: text("result"),
    metric: text("metric"),
    sourceNote: text("source_note"),
    sourceUrl: text("source_url"),
    reviewed: boolean("reviewed").notNull().default(false),
    ...timestamps,
  },
  (t) => [
    unique("achievements_profile_id_id_unique").on(t.profileId, t.id),
    foreignKey({
      name: "achievements_employment_fk",
      columns: [t.profileId, t.employmentId],
      foreignColumns: [employment.profileId, employment.id],
    }).onDelete("restrict"),
    foreignKey({
      name: "achievements_project_fk",
      columns: [t.profileId, t.projectId],
      foreignColumns: [projects.profileId, projects.id],
    }).onDelete("restrict"),
    index("achievements_profile_id_employment_id_idx").on(t.profileId, t.employmentId),
    index("achievements_profile_id_project_id_idx").on(t.profileId, t.projectId),
    notBlank("achievements", t.statement.name),
    check("achievements_single_context", sql`employment_id IS NULL OR project_id IS NULL`),
  ],
);

export const skills = pgTable(
  "skills",
  {
    id: uuid("id").primaryKey(),
    profileId: uuid("profile_id")
      .notNull()
      .references(() => profiles.id, { onDelete: "cascade" }),
    displayName: text("display_name").notNull(),
    normalizedName: text("normalized_name").notNull(),
    category: text("category"),
    ...timestamps,
  },
  (t) => [
    unique("skills_profile_id_id_unique").on(t.profileId, t.id),
    unique("skills_profile_id_normalized_name_unique").on(t.profileId, t.normalizedName),
    notBlank("skills", t.displayName.name),
    notBlank("skills", t.normalizedName.name),
  ],
);

export const achievementSkills = pgTable(
  "achievement_skills",
  {
    profileId: uuid("profile_id").notNull(),
    achievementId: uuid("achievement_id").notNull(),
    skillId: uuid("skill_id").notNull(),
  },
  (t) => [
    primaryKey({ columns: [t.achievementId, t.skillId] }),
    foreignKey({
      name: "achievement_skills_achievement_fk",
      columns: [t.profileId, t.achievementId],
      foreignColumns: [achievements.profileId, achievements.id],
    }).onDelete("cascade"),
    foreignKey({
      name: "achievement_skills_skill_fk",
      columns: [t.profileId, t.skillId],
      foreignColumns: [skills.profileId, skills.id],
    }).onDelete("cascade"),
    index("achievement_skills_profile_id_skill_id_idx").on(t.profileId, t.skillId),
  ],
);
