import { sql } from "drizzle-orm";
import {
  check,
  foreignKey,
  index,
  integer,
  primaryKey,
  sqliteTable,
  text,
  unique,
} from "drizzle-orm/sqlite-core";
import { educationStatuses } from "./contracts";

/*
 * Phase 0 tables (docs/04). Rules the database backs up:
 * - Every owned record carries profile_id. Child links use owner-aware composite foreign keys
 *   (profile_id, linked_id) -> parent (profile_id, id), so a link cannot cross profiles.
 * - An achievement has at most one context: employment or project, never both.
 * - Skill names are unique per profile after normalization.
 * - Dates are month precision: year and month are paired (both null or both set), month 1-12.
 * - Deleting employment or a project with dependent facts is restricted; deleting an achievement
 *   or a skill removes only its join rows. Deleting a profile removes everything it owns.
 * UUIDs are generated by the application and stored as text; timestamps are integer milliseconds.
 */

const timestamps = {
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull(),
};

const monthDates = {
  startYear: integer("start_year"),
  startMonth: integer("start_month"),
  endYear: integer("end_year"),
  endMonth: integer("end_month"),
};

/** Check constraints for a pair of month-only start/end dates. */
function monthDateChecks(table: string) {
  return [
    check(`${table}_start_month_pair`, sql`(start_year IS NULL) = (start_month IS NULL)`),
    check(`${table}_end_month_pair`, sql`(end_year IS NULL) = (end_month IS NULL)`),
    check(
      `${table}_start_month_range`,
      sql`start_month IS NULL OR (start_month BETWEEN 1 AND 12 AND start_year BETWEEN 1900 AND 2100)`,
    ),
    check(
      `${table}_end_month_range`,
      sql`end_month IS NULL OR (end_month BETWEEN 1 AND 12 AND end_year BETWEEN 1900 AND 2100)`,
    ),
    check(
      `${table}_end_not_before_start`,
      sql`start_year IS NULL OR end_year IS NULL OR (end_year * 12 + end_month) >= (start_year * 12 + start_month)`,
    ),
  ];
}

const notBlank = (table: string, column: string) =>
  check(`${table}_${column}_not_blank`, sql.raw(`trim(${column}) <> ''`));

/** Public links for the resume header (Phase 1b): LinkedIn, GitHub, a website. */
export interface ProfileLinkRecord {
  label: string;
  url: string;
}

export interface ProfilePreferences {
  desiredRoles?: string[];
  locations?: string[];
  workArrangement?: ("remote" | "hybrid" | "onsite")[];
  constraints?: string;
  resumeContacts?: ("phone" | "email" | "location" | "linkedin" | "github" | "website")[];
}

export const profiles = sqliteTable(
  "profiles",
  {
    id: text("id").primaryKey(),
    displayName: text("display_name").notNull(),
    headline: text("headline"),
    summary: text("summary"),
    aboutMe: text("about_me"),
    email: text("email"),
    phone: text("phone"),
    location: text("location"),
    preferences: text("preferences", { mode: "json" })
      .$type<ProfilePreferences>()
      .notNull()
      .default({}),
    links: text("links", { mode: "json" }).$type<ProfileLinkRecord[]>().notNull().default([]),
    ...timestamps,
  },
  (t) => [notBlank("profiles", t.displayName.name)],
);

export const employment = sqliteTable(
  "employment",
  {
    id: text("id").primaryKey(),
    profileId: text("profile_id")
      .notNull()
      .references(() => profiles.id, { onDelete: "cascade" }),
    employerName: text("employer_name").notNull(),
    role: text("role").notNull(),
    location: text("location"),
    ...monthDates,
    isCurrent: integer("is_current", { mode: "boolean" }).notNull().default(false),
    description: text("description"),
    ...timestamps,
  },
  (t) => [
    unique("employment_profile_id_id_unique").on(t.profileId, t.id),
    notBlank("employment", t.employerName.name),
    notBlank("employment", t.role.name),
    ...monthDateChecks("employment"),
  ],
);

export const education = sqliteTable(
  "education",
  {
    id: text("id").primaryKey(),
    profileId: text("profile_id")
      .notNull()
      .references(() => profiles.id, { onDelete: "cascade" }),
    institution: text("institution").notNull(),
    qualification: text("qualification"),
    subject: text("subject"),
    ...monthDates,
    status: text("status", { enum: educationStatuses }).notNull().default("completed"),
    description: text("description"),
    ...timestamps,
  },
  (t) => [
    index("education_profile_id_idx").on(t.profileId),
    notBlank("education", t.institution.name),
    check("education_status_valid", sql`status IN ('in_progress', 'completed', 'incomplete')`),
    ...monthDateChecks("education"),
  ],
);

export const projects = sqliteTable(
  "projects",
  {
    id: text("id").primaryKey(),
    profileId: text("profile_id")
      .notNull()
      .references(() => profiles.id, { onDelete: "cascade" }),
    employmentId: text("employment_id"),
    name: text("name").notNull(),
    description: text("description"),
    url: text("url"),
    ...monthDates,
    ...timestamps,
  },
  (t) => [
    unique("projects_profile_id_id_unique").on(t.profileId, t.id),
    foreignKey({
      name: "projects_employment_fk",
      columns: [t.profileId, t.employmentId],
      foreignColumns: [employment.profileId, employment.id],
    }).onDelete("restrict"),
    index("projects_profile_id_employment_id_idx").on(t.profileId, t.employmentId),
    notBlank("projects", t.name.name),
    ...monthDateChecks("projects"),
  ],
);

export const achievements = sqliteTable(
  "achievements",
  {
    id: text("id").primaryKey(),
    profileId: text("profile_id")
      .notNull()
      .references(() => profiles.id, { onDelete: "cascade" }),
    employmentId: text("employment_id"),
    projectId: text("project_id"),
    statement: text("statement").notNull(),
    problem: text("problem"),
    action: text("action"),
    result: text("result"),
    metric: text("metric"),
    sourceNote: text("source_note"),
    sourceUrl: text("source_url"),
    reviewed: integer("reviewed", { mode: "boolean" }).notNull().default(false),
    ...timestamps,
  },
  (t) => [
    unique("achievements_profile_id_id_unique").on(t.profileId, t.id),
    foreignKey({
      name: "achievements_employment_fk",
      columns: [t.profileId, t.employmentId],
      foreignColumns: [employment.profileId, employment.id],
    }).onDelete("restrict"),
    foreignKey({
      name: "achievements_project_fk",
      columns: [t.profileId, t.projectId],
      foreignColumns: [projects.profileId, projects.id],
    }).onDelete("restrict"),
    index("achievements_profile_id_employment_id_idx").on(t.profileId, t.employmentId),
    index("achievements_profile_id_project_id_idx").on(t.profileId, t.projectId),
    notBlank("achievements", t.statement.name),
    check("achievements_single_context", sql`employment_id IS NULL OR project_id IS NULL`),
  ],
);

export const skills = sqliteTable(
  "skills",
  {
    id: text("id").primaryKey(),
    profileId: text("profile_id")
      .notNull()
      .references(() => profiles.id, { onDelete: "cascade" }),
    displayName: text("display_name").notNull(),
    normalizedName: text("normalized_name").notNull(),
    category: text("category"),
    ...timestamps,
  },
  (t) => [
    unique("skills_profile_id_normalized_name_unique").on(t.profileId, t.normalizedName),
    // Declared last so SQLite checks it first and a retried id reports it (mapDatabaseError).
    unique("skills_profile_id_id_unique").on(t.profileId, t.id),
    notBlank("skills", t.displayName.name),
    notBlank("skills", t.normalizedName.name),
  ],
);

export const achievementSkills = sqliteTable(
  "achievement_skills",
  {
    profileId: text("profile_id").notNull(),
    achievementId: text("achievement_id").notNull(),
    skillId: text("skill_id").notNull(),
  },
  (t) => [
    primaryKey({ columns: [t.achievementId, t.skillId] }),
    foreignKey({
      name: "achievement_skills_achievement_fk",
      columns: [t.profileId, t.achievementId],
      foreignColumns: [achievements.profileId, achievements.id],
    }).onDelete("cascade"),
    foreignKey({
      name: "achievement_skills_skill_fk",
      columns: [t.profileId, t.skillId],
      foreignColumns: [skills.profileId, skills.id],
    }).onDelete("cascade"),
    index("achievement_skills_profile_id_skill_id_idx").on(t.profileId, t.skillId),
  ],
);

/** Direct, user-maintained skill context; achievement-derived associations are not stored here. */
export const skillEmployment = sqliteTable(
  "skill_employment",
  {
    profileId: text("profile_id").notNull(),
    skillId: text("skill_id").notNull(),
    employmentId: text("employment_id").notNull(),
  },
  (t) => [
    primaryKey({ columns: [t.skillId, t.employmentId] }),
    foreignKey({
      name: "skill_employment_skill_fk",
      columns: [t.profileId, t.skillId],
      foreignColumns: [skills.profileId, skills.id],
    }).onDelete("cascade"),
    foreignKey({
      name: "skill_employment_role_fk",
      columns: [t.profileId, t.employmentId],
      foreignColumns: [employment.profileId, employment.id],
    }).onDelete("restrict"),
    index("skill_employment_profile_role_idx").on(t.profileId, t.employmentId),
  ],
);
export const skillProjects = sqliteTable(
  "skill_projects",
  {
    profileId: text("profile_id").notNull(),
    skillId: text("skill_id").notNull(),
    projectId: text("project_id").notNull(),
  },
  (t) => [
    primaryKey({ columns: [t.skillId, t.projectId] }),
    foreignKey({
      name: "skill_projects_skill_fk",
      columns: [t.profileId, t.skillId],
      foreignColumns: [skills.profileId, skills.id],
    }).onDelete("cascade"),
    foreignKey({
      name: "skill_projects_project_fk",
      columns: [t.profileId, t.projectId],
      foreignColumns: [projects.profileId, projects.id],
    }).onDelete("restrict"),
    index("skill_projects_profile_project_idx").on(t.profileId, t.projectId),
  ],
);
